# Generated by Django 6.0.2 on 2026-02-16 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GreenhouseZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZoneThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_temp_min", models.FloatField(default=20.0)),
                ("target_temp_max", models.FloatField(default=30.0)),
                ("target_humidity_min", models.FloatField(default=40.0)),
                ("target_humidity_max", models.FloatField(default=70.0)),
                ("min_moisture", models.FloatField(default=40.0)),
                ("max_moisture", models.FloatField(default=80.0)),
                (
                    "zone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold",
                        to="greenhouse.greenhousezone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("soil_moisture", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_alert", models.BooleanField(default=False, editable=False)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="greenhouse.greenhousezone",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zone", "-timestamp"],
                        name="greenhouse__zone_id_6ed6fa_idx",
                    )
                ],
            },
        ),
    ]
